name: acme.bookstore
services:
- name: acme-bookstore-web
  project: src/Acme.BookStore.Web/Acme.BookStore.Web.csproj
  bindings:
  - protocol: https
    port: 44342
- name: acme-bookstore-identityserver
  project: src/Acme.BookStore.IdentityServer/Acme.BookStore.IdentityServer.csproj
  bindings:
  - protocol: https
    port: 44345
- name: acme-bookstore-httpapi-host
  project: src/Acme.BookStore.HttpApi.Host/Acme.BookStore.HttpApi.Host.csproj
  bindings:
  - protocol: https
    port: 44354
- name: redis
  image: redis
  replicas: 1
  bindings:
    - containerPort: 6379
      port: 6379
  volumes:
    - source: AppData/Redis/data
      target: /data/
- name: sqlserver
  image: mcr.microsoft.com/mssql/server:2019-latest
  bindings:
  - containerPort: 1433
    port: 1433
  env:
  - ACCEPT_EULA=Y
  - SA_PASSWORD=Abcd1234
  - MSSQL_PID=Express
  # volumes appear here
  volumes:
    - source: AppData/SqlServer/data
      target: /var/opt/mssql/data